name: flutter_arduino
description: Flutter Arduino project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  intl: 0.19.0

  #---NETWORK DATA---#
  firebase_core: 2.25.3
  firebase_auth: 4.17.3
  firebase_database: 10.4.4

  #---STATE MANAGEMENT---#
  flutter_riverpod: 2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
